# Generated by Django 4.2.11 on 2025-02-11 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('image', models.ImageField(upload_to='cases/')),
            ],
            options={
                'db_table': 'cases',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=500)),
                ('password', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_blocked', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='CaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('flag', models.TextField()),
                ('flag_layout', models.CharField(max_length=255)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.case')),
            ],
            options={
                'db_table': 'case_steps',
            },
        ),
        migrations.CreateModel(
            name='CaseOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.user')),
            ],
            options={
                'db_table': 'case_ownerships',
            },
        ),
    ]
