# Generated by Django 4.2.11 on 2025-02-11 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('solved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(default=0)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.casestep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='web.user')),
            ],
            options={
                'db_table': 'case_activties',
            },
        ),
    ]
