# Generated by Django 4.2.11 on 2025-02-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('logo', models.ImageField(upload_to='services/')),
            ],
            options={
                'db_table': 'services',
            },
        ),
    ]
